import { readFile, writeFile, mkdir } from 'node:fs/promises';
import type { BenchReport } from './accuracy.ts';

/**
 * Turns the benchmark JSON into a Markdown table and an SVG chart.
 *
 * The SVG is written by hand rather than with a charting library: it is two
 * bar charts, and a dependency that pulls in a rendering engine to draw
 * rectangles is a dependency to explain in every future audit.
 */
const BAR_WIDTH = 460;
const ROW_HEIGHT = 34;

function bar(
  label: string,
  value: number,
  max: number,
  y: number,
  colour: string,
  suffix: string,
): string {
  const width = Math.max(2, Math.round((value / max) * BAR_WIDTH));
  return `  <text x="0" y="${String(y + 14)}" class="label">${label}</text>
  <rect x="130" y="${String(y)} " width="${String(width)}" height="18" fill="${colour}" rx="2" />
  <text x="${String(136 + width)}" y="${String(y + 14)}" class="value">${String(value)}${suffix}</text>`;
}

export function renderSvg(report: BenchReport): string {
  const boundaryMax = Math.max(...report.boundary.map((result) => result.overshoot), 2);
  const memoryMax = Math.max(...report.cost.map((result) => result.bytesPerClient));

  const boundaryRows = report.boundary.map((result, index) =>
    bar(result.strategy, result.overshoot, boundaryMax, 50 + index * ROW_HEIGHT, '#c2410c', '×'),
  );
  const memoryRows = report.cost.map((result, index) =>
    bar(
      result.strategy,
      result.bytesPerClient,
      memoryMax,
      220 + index * ROW_HEIGHT,
      '#1d4ed8',
      ' B',
    ),
  );

  return `<svg xmlns="http://www.w3.org/2000/svg" width="700" height="340" viewBox="0 0 700 340" role="img" aria-label="Boundary overshoot and memory per client by strategy">
  <style>
    text { font: 13px system-ui, sans-serif; fill: #111; }
    .title { font-weight: 600; font-size: 15px; }
    .note { fill: #555; font-size: 12px; }
    @media (prefers-color-scheme: dark) { text { fill: #eee; } .note { fill: #aaa; } }
  </style>
  <text x="0" y="20" class="title">Allowance let through across a window boundary</text>
  <text x="0" y="38" class="note">1.0× is exact. Higher is worse.</text>
${boundaryRows.join('\n')}
  <text x="0" y="190" class="title">Redis memory per active client</text>
  <text x="0" y="208" class="note">Sliding log grows with the request rate, not the client count.</text>
${memoryRows.join('\n')}
</svg>
`;
}

export function renderMarkdown(report: BenchReport): string {
  const boundary = report.boundary.map(
    (result) =>
      `| \`${result.strategy}\` | ${String(result.allowedAcrossBoundary)} | ${String(result.ideal)} | **${result.overshoot.toFixed(2)}×** |`,
  );
  const cost = report.cost.map(
    (result) =>
      `| \`${result.strategy}\` | ${String(result.commandsPerDecision)} | ${String(result.bytesPerClient)} B | ${String(result.p50Ms)} ms | ${String(result.p99Ms)} ms |`,
  );

  const worst = [...report.boundary].sort((a, b) => b.overshoot - a.overshoot)[0];
  const heaviest = [...report.cost].sort((a, b) => b.bytesPerClient - a.bytesPerClient)[0];
  const lightest = [...report.cost].sort((a, b) => a.bytesPerClient - b.bytesPerClient)[0];

  return `# Benchmark results

Generated by \`npm run bench:accuracy && npm run bench:render\`. Do not edit by
hand.

- Run at ${report.generatedAt.slice(0, 19).replace('T', ' ')} UTC on ${report.machine}, Redis ${report.redisVersion}.
- Limit ${String(report.parameters.limit)} per ${String(report.parameters.windowMs)} ms; ${String(report.parameters.clients)} clients × ${String(report.parameters.requestsPerClient)} requests for the cost run.
- Method and what these numbers do **not** claim: [METHODOLOGY.md](../../bench/METHODOLOGY.md).

![Boundary overshoot and memory per client by strategy](chart.svg)

## Accuracy at a window boundary

The whole allowance is spent in the last moment of one window and again in the
first moment of the next. A true sliding window allows \`limit\` across that
span; anything more is allowance the client should not have had.

| strategy | allowed across the boundary | ideal | overshoot |
| --- | ---: | ---: | ---: |
${boundary.join('\n')}

\`${worst?.strategy ?? ''}\` let through ${worst?.overshoot.toFixed(2) ?? ''}× the limit. That is not a bug to tune away —
it is what a clock-aligned window means, and the only fix is a different
algorithm.

## Cost per decision

| strategy | Redis commands | memory per client | p50 | p99 |
| --- | ---: | ---: | ---: | ---: |
${cost.join('\n')}

The command counts include the calls each Lua script makes internally, which is
why a one-round-trip decision still costs five or more: the script itself,
\`TIME\`, and the reads and writes it performs.

\`${heaviest?.strategy ?? ''}\` uses ${String(Math.round((heaviest?.bytesPerClient ?? 0) / Math.max(1, lightest?.bytesPerClient ?? 1)))}× the memory of \`${lightest?.strategy ?? ''}\` per client, and that ratio
grows with the limit rather than staying fixed: it keeps one sorted-set member
per accepted request, so a limit of 1,000 per minute is 1,000 members per
active client.

Latency is measured against a Redis on the same machine and is a floor, not a
production figure. The comparison between strategies is the part that carries
over; the absolute numbers do not.
`;
}

const input = new URL('results/accuracy.json', import.meta.url);
const report = JSON.parse(await readFile(input, 'utf8')) as BenchReport;
const outDir = new URL('../docs/bench/', import.meta.url);

await mkdir(outDir, { recursive: true });
await writeFile(new URL('chart.svg', outDir), renderSvg(report));
await writeFile(new URL('README.md', outDir), renderMarkdown(report));
console.log('wrote docs/bench/README.md and docs/bench/chart.svg');
